In [1]:
import warnings
warnings.simplefilter('ignore')

# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import imblearn
import smote_variants as sv
#import imbalanced_databases as imbd

In [13]:
clean_df = pd.read_csv('Resources/Final_Clean2.csv')
clean_df.dropna()

,NPA,year,Petitioner,FromZone,ToZone,Type,SPA,INNOV,Acres,Water,...,student_absenteeism,voters_participating,neighborhood_organizations,voter_participation,vacant_land,population_density,population,transit_ridership,street_connectivity,bicycle_friendliness
0,2,2020,Alenky Signature Homes LLC,R-4,R-8,NC,no,NO,0.398,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
1,2,2019,Mark Heisig,O-2,R-4,NC,no,NO,0.330,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
2,2,2014,"Eastway II Holdings, LLC",BD(CD),BD(CD),CD,SPA,NO,3.050,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
3,2,2014,"Eastway II Holdings, LLC",B-1SCD,BD(CD),CD,no,NO,3.740,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
4,2,2016,"Dr. Michael Berglass, DDS",UR-C(CD),UR-C(CD),CD,SPA,NO,0.440,CMUD,...,15.000000,1063.000000,2.0,76.000000,4.3,5.0,2240.0,43.0,1.2,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,437,2014,Charlotte-Mecklenburg Planning Department,No Zoning,R-4,NC,no,NO,6.770,CMUD,...,10.000000,855.000000,-1.0,53.000000,-1.0,-1.0,-1.0,4.0,-1.0,-1.0
1753,443,2014,"Southern Apartment Group - Ballantyne, LLC",R-8MF(CD),NS,CD,no,NO,3.780,CMUD,...,4.807692,370.000000,-1.0,52.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1754,443,2019,"Ascent Real Estate Capital, LLC",NS,NS,CD,SPA,NO,3.420,CMUD,...,4.807692,370.000000,-1.0,52.000000,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1755,444,2016,"Newman-Tillman Properties, LLC",O-1(CD),BD(CD),CD,no,NO,5.350,CMUD,...,9.000000,1072.000000,-1.0,77.000000,15.6,6.0,2238.0,-1.0,1.0,1.1
1756,444,2016,"Newman-Tillman Properties, LLC",O-1(CD),R-3(CD),CD,no,NO,1.480,CMUD,...,9.000000,1072.000000,-1.0,77.000000,15.6,6.0,2238.0,-1.0,1.0,1.1

In [14]:
clean_df.head()

,NPA,year,Petitioner,FromZone,ToZone,Type,SPA,INNOV,Acres,Water,...,student_absenteeism,voters_participating,neighborhood_organizations,voter_participation,vacant_land,population_density,population,transit_ridership,street_connectivity,bicycle_friendliness
0,2,2020,Alenky Signature Homes LLC,R-4,R-8,NC,no,NO,0.398,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
1,2,2019,Mark Heisig,O-2,R-4,NC,no,NO,0.330,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
2,2,2014,"Eastway II Holdings, LLC",BD(CD),BD(CD),CD,SPA,NO,3.050,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
3,2,2014,"Eastway II Holdings, LLC",B-1SCD,BD(CD),CD,no,NO,3.740,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
4,2,2016,"Dr. Michael Berglass, DDS",UR-C(CD),UR-C(CD),CD,SPA,NO,0.440,CMUD,...,15.000000,1063.000000,2.0,76.000000,4.3,5.0,2240.0,43.0,1.2,1.5

In [15]:
clean_df.head()

,NPA,year,Petitioner,FromZone,ToZone,Type,SPA,INNOV,Acres,Water,...,student_absenteeism,voters_participating,neighborhood_organizations,voter_participation,vacant_land,population_density,population,transit_ridership,street_connectivity,bicycle_friendliness
0,2,2020,Alenky Signature Homes LLC,R-4,R-8,NC,no,NO,0.398,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
1,2,2019,Mark Heisig,O-2,R-4,NC,no,NO,0.330,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
2,2,2014,"Eastway II Holdings, LLC",BD(CD),BD(CD),CD,SPA,NO,3.050,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
3,2,2014,"Eastway II Holdings, LLC",B-1SCD,BD(CD),CD,no,NO,3.740,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
4,2,2016,"Dr. Michael Berglass, DDS",UR-C(CD),UR-C(CD),CD,SPA,NO,0.440,CMUD,...,15.000000,1063.000000,2.0,76.000000,4.3,5.0,2240.0,43.0,1.2,1.5

In [16]:
clean_df.dtypes
clean_df.count()

NPA                               1757
year                              1757
Petitioner                        1757
FromZone                          1757
ToZone                            1757
Type                              1757
SPA                               1757
INNOV                             1757
Acres                             1757
Water                             1757
Sewer                             1757
CityLimit                         1757
CCW                               1757
ServiceArea                       1757
LuseStaff                         1757
UrbanDesign                       1757
RezoneStaff                       1757
Received                          1757
Approved                          1757
Decision                          1757
births_to_adolescents             1757
grocery_proximate_units           1757
prenatal_care                     1757
grocery_proximity                 1757
low_birthweight                   1757
public_health_insurance           1757
age_of_death                      1757
impervious_surface                1757
water_consumption                 1757
neighborhood_school_attendance    1757
highschool_graduation_rate        1757
proficiency_elementary_school     1757
proficiency_middle_school         1757
proficiency_high_school           1757
student_absenteeism               1757
voters_participating              1757
neighborhood_organizations        1757
voter_participation               1757
vacant_land                       1757
population_density                1757
population                        1757
transit_ridership                 1757
street_connectivity               1757
bicycle_friendliness              1757
dtype: int64

In [17]:
column_names = list(clean_df.columns.values)
print(column_names)
len(column_names)

['NPA', 'year', 'Petitioner', 'FromZone', 'ToZone', 'Type', 'SPA', 'INNOV', 'Acres', 'Water', 'Sewer', 'CityLimit', 'CCW', 'ServiceArea', 'LuseStaff', 'UrbanDesign', 'RezoneStaff', 'Received', 'Approved', 'Decision', 'births_to_adolescents', 'grocery_proximate_units', 'prenatal_care', 'grocery_proximity', 'low_birthweight', 'public_health_insurance', 'age_of_death', 'impervious_surface', 'water_consumption', 'neighborhood_school_attendance', 'highschool_graduation_rate', 'proficiency_elementary_school', 'proficiency_middle_school', 'proficiency_high_school', 'student_absenteeism', 'voters_participating', 'neighborhood_organizations', 'voter_participation', 'vacant_land', 'population_density', 'population', 'transit_ridership', 'street_connectivity', 'bicycle_friendliness']

44

In [18]:
#catagorical_columns drop 'Decision', which will be our Target
catagorical_columns = ['NPA', 'year', 'Petitioner', 'FromZone', 'ToZone', 'Type', 'SPA', 'INNOV', 'Water', 'Sewer', 'CityLimit', 'CCW', 'ServiceArea', 'LuseStaff', 'UrbanDesign', 'RezoneStaff', 'Received', 'Approved']
numberic_columns = ['Acres', 'births_to_adolescents', 'grocery_proximate_units', 'prenatal_care', 'grocery_proximity',
                  'low_birthweight', 'public_health_insurance', 'age_of_death', 'impervious_surface',
                  'water_consumption', 'neighborhood_school_attendance', 'highschool_graduation_rate', 
                   'proficiency_elementary_school', 'proficiency_middle_school', 'proficiency_high_school',
                   'student_absenteeism', 'voters_participating', 'neighborhood_organizations',
                   'voter_participation', 'vacant_land', 'population_density', 'population', 'transit_ridership',
                   'street_connectivity', 'bicycle_friendliness']
all_columns = ['NPA', 'year', 'Petitioner', 'FromZone', 'ToZone', 'Type', 'SPA', 'INNOV', 'Acres', 'Water', 'Sewer', 'CityLimit', 'CCW', 'ServiceArea', 'LuseStaff', 'UrbanDesign', 'RezoneStaff', 'Received', 'Approved', 'Decision', 'births_to_adolescents', 'grocery_proximate_units', 'prenatal_care', 'grocery_proximity', 'low_birthweight', 'public_health_insurance', 'age_of_death', 'impervious_surface', 'water_consumption', 'neighborhood_school_attendance', 'highschool_graduation_rate', 'proficiency_elementary_school', 'proficiency_middle_school', 'proficiency_high_school', 'student_absenteeism', 'voters_participating', 'neighborhood_organizations', 'voter_participation', 'vacant_land', 'population_density', 'population', 'transit_ridership', 'street_connectivity', 'bicycle_friendliness']

In [19]:
print(len(catagorical_columns))
print(len(numberic_columns))
print("______")
print(len(catagorical_columns)+len(numberic_columns))
print("______")
print(len(clean_df.columns))

18
25
______
43
______
44

In [20]:
y = clean_df[['Decision']]
y.head()

  Decision
0      App
1      App
2      App
3      App
4      App

In [21]:
clean_drop_df = clean_df.copy().drop(["Decision"], axis=1)
clean_drop_df.head()

,NPA,year,Petitioner,FromZone,ToZone,Type,SPA,INNOV,Acres,Water,...,student_absenteeism,voters_participating,neighborhood_organizations,voter_participation,vacant_land,population_density,population,transit_ridership,street_connectivity,bicycle_friendliness
0,2,2020,Alenky Signature Homes LLC,R-4,R-8,NC,no,NO,0.398,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
1,2,2019,Mark Heisig,O-2,R-4,NC,no,NO,0.330,CMUD,...,12.666667,756.333333,2.0,61.333333,4.3,5.0,2240.0,43.0,1.2,1.5
2,2,2014,"Eastway II Holdings, LLC",BD(CD),BD(CD),CD,SPA,NO,3.050,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
3,2,2014,"Eastway II Holdings, LLC",B-1SCD,BD(CD),CD,no,NO,3.740,CMUD,...,11.500000,603.000000,2.0,54.000000,4.3,5.0,2240.0,43.0,1.2,1.5
4,2,2016,"Dr. Michael Berglass, DDS",UR-C(CD),UR-C(CD),CD,SPA,NO,0.440,CMUD,...,15.000000,1063.000000,2.0,76.000000,4.3,5.0,2240.0,43.0,1.2,1.5

In [22]:
#Dummy Encode Catagorical Data
X = pd.get_dummies(clean_drop_df, columns=catagorical_columns)
X.head()

,Acres,births_to_adolescents,grocery_proximate_units,prenatal_care,grocery_proximity,low_birthweight,public_health_insurance,age_of_death,impervious_surface,water_consumption,...,Approved_2020/05/18 00:00:00+00,Approved_2020/05/18 16:02:33+00,Approved_2020/05/18 16:18:00+00,Approved_2020/05/18 16:38:34+00,Approved_2020/05/18 16:38:48+00,Approved_2020/05/18 16:46:28+00,Approved_2020/05/18 16:48:49+00,Approved_2020/06/15 00:00:00+00,Approved_2020/07/20 00:00:00+00,Approved_UKN
0,0.398,3.166667,204.333333,70.466667,19.0,17.733333,13.0,68.666667,22.2,112.333333,...,0,0,0,0,0,0,0,0,1,0
1,0.330,3.166667,204.333333,70.466667,19.0,17.733333,13.0,68.666667,22.2,112.333333,...,0,0,0,0,0,0,0,0,0,0
2,3.050,1.400000,204.000000,75.700000,19.0,21.600000,13.0,68.000000,22.2,112.000000,...,0,0,0,0,0,0,0,0,0,0
3,3.740,1.400000,204.000000,75.700000,19.0,21.600000,13.0,68.000000,22.2,112.000000,...,0,0,0,0,0,0,0,0,0,0
4,0.440,6.700000,205.000000,60.000000,19.0,10.000000,13.0,70.000000,22.2,113.000000,...,0,0,0,0,0,0,0,0,0,0

In [49]:
# Does not seem to work
#oversampler = sv.distance_SMOTE()
#x_samp , y_samp= oversampler.sample(X,y)

In [24]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

label_encoder.fit(y)
label_encoder.classes_

array(['App', 'Def', 'Den', 'UKN', 'Wd'], dtype=object)

In [25]:
encoded_y = label_encoder.transform(y)
print(encoded_y)

[0 0 0 ... 0 0 0]

In [28]:
print(X.shape, encoded_y.shape)

(1757, 2091) (1757,)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=42)

#print(X_train.head())
#print(y_train[0:5])

In [31]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
# logistic regression object 
lr = LogisticRegression() 
  
# train the model on train set 
lr.fit(X_train_scaled, y_train.ravel()) 
  
predictions = lr.predict(X_test) 
  
# print classification report 
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.88      0.02      0.03       406
           2       0.01      1.00      0.03         6
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        27

    accuracy                           0.03       440
   macro avg       0.22      0.25      0.02       440
weighted avg       0.81      0.03      0.03       440

In [47]:
print("Before OverSampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train == 0))) 
  
# import SMOTE module from imblearn library 
# pip install imblearn (if you don't have imblearn in your system) 
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2, k_neighbors=1) 
X_train_res, y_train_res = sm.fit_sample(X_train_scaled, y_train.ravel()) 
  
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

Before OverSampling, counts of label '1': 2
Before OverSampling, counts of label '0': 1198

After OverSampling, the shape of train_X: (5990, 2091)
After OverSampling, the shape of train_y: (5990,)

After OverSampling, counts of label '1': 1198
After OverSampling, counts of label '0': 1198

In [48]:
lr1 = LogisticRegression() 
lr1.fit(X_train_res, y_train_res.ravel()) 
predictions = lr1.predict(X_test) 
  
# print classification report 
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.80      0.01      0.02       406
           2       0.01      1.00      0.03         6
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        27

    accuracy                           0.02       440
   macro avg       0.20      0.25      0.01       440
weighted avg       0.74      0.02      0.02       440

# Why Does smote provide worse results

Overlapping could be the reason. If there is an overlapping between the classes given the variables you have, SMOTE would be generating synthetic points affecting the separability.